apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portfolio-ing
  annotations: {}
spec:
  ingressClassName: nginx
  rules:
    - host: portfolio.local
      http:
        paths:
          - path: /_next/
            pathType: Prefix
            backend:
              service:
                name: portfolio-svc
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: portfolio-svc
                port:
                  number: 80
